<a href="https://colab.research.google.com/github/shindeaditya/Data-Science/blob/main/disneyland_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Kaggle linking

In [ ]:
! pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.9/dist-packages (1.5.13)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.9/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from kaggle) (2.27.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from kaggle) (1.26.15)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.9/dist-packages (from kaggle) (8.0.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from kaggle) (4.65.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.9/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle) (2.0.12)

In [ ]:
!mkdir -p ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download arushchillar/disneyland-reviews

Downloading disneyland-reviews.zip to /content
  0% 0.00/11.1M [00:00<?, ?B/s]
100% 11.1M/11.1M [00:00<00:00, 144MB/s]

In [ ]:
! unzip disneyland-reviews.zip

Archive:  disneyland-reviews.zip
  inflating: DisneylandReviews.csv

 Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import nltk
import string

In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [ ]:
dlrev=pd.read_csv('/content/DisneylandReviews.csv', encoding='latin-1')
dlrev.head()

,Review_ID,Rating,Year_Month,Reviewer_Location,Review_Text,Branch
0,670772142,4,2019-4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,670682799,4,2019-5,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,670623270,4,2019-4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,670607911,4,2019-4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,670607296,4,2019-4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong

In [ ]:
dlrev.shape

(42656, 6)

In [ ]:
df=dlrev[['Rating','Reviewer_Location','Review_Text','Branch']]
df.head()

,Rating,Reviewer_Location,Review_Text,Branch
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong

# Removing Punctuations

In [ ]:
def remove_punc(sentence):
    text="".join([i for i in sentence if i not in string.punctuation])
    return text

df['text']=df['Review_Text'].apply(lambda x:remove_punc(x))
df.head()

<ipython-input-12-72f26cf41813>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text']=df['Review_Text'].apply(lambda x:remove_punc(x))

,Rating,Reviewer_Location,Review_Text,Branch,text
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,If youve ever been to Disneyland anywhere youl...
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,Its been a while since d last time we visit HK...
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,Thanks God it wasn t too hot or too humid wh...
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,HK Disneyland is a great compact park Unfortun...
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,the location is not in the city took around 1 ...

# Lower casing sentences

In [ ]:
df['text']=df['text'].apply(lambda x:x.lower())
df.head()

<ipython-input-13-514f4a62ed7f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text']=df['text'].apply(lambda x:x.lower())

,Rating,Reviewer_Location,Review_Text,Branch,text
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,if youve ever been to disneyland anywhere youl...
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,its been a while since d last time we visit hk...
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god it wasn t too hot or too humid wh...
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland is a great compact park unfortun...
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,the location is not in the city took around 1 ...

# Removing Stopwords

In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
df['text'] = df['text'].apply(lambda x : " ".join(x for x in x.split() if x not in stop))
df.head()

<ipython-input-14-2252aaa31972>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].apply(lambda x : " ".join(x for x in x.split() if x not in stop))

,Rating,Reviewer_Location,Review_Text,Branch,text
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland great compact park unfortunately...
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,location city took around 1 hour kowlon kids l...

# Tokenization

In [ ]:
from nltk.tokenize import word_tokenize
def tokenize(sentence):
    words=word_tokenize(sentence)
    return words
df['word']=df['text'].apply(lambda x:tokenize(x))
df.head()

,Rating,Reviewer_Location,Review_Text,Branch,text,word
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...,"[youve, ever, disneyland, anywhere, youll, fin..."
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...,"[since, last, time, visit, hk, disneyland, yet..."
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...,"[thanks, god, hot, humid, visiting, park, othe..."
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland great compact park unfortunately...,"[hk, disneyland, great, compact, park, unfortu..."
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,location city took around 1 hour kowlon kids l...,"[location, city, took, around, 1, hour, kowlon..."

# Stemming

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stemming(list):
    stem_text = [ps.stem(word) for word in list]
    return stem_text

df['stem']=df['word'].apply(lambda x:stemming(x))
df.head()

,Rating,Reviewer_Location,Review_Text,Branch,text,word,stem
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...,"[youve, ever, disneyland, anywhere, youll, fin...","[youv, ever, disneyland, anywher, youll, find,..."
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...,"[since, last, time, visit, hk, disneyland, yet...","[sinc, last, time, visit, hk, disneyland, yet,..."
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...,"[thanks, god, hot, humid, visiting, park, othe...","[thank, god, hot, humid, visit, park, otherwis..."
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland great compact park unfortunately...,"[hk, disneyland, great, compact, park, unfortu...","[hk, disneyland, great, compact, park, unfortu..."
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,location city took around 1 hour kowlon kids l...,"[location, city, took, around, 1, hour, kowlon...","[locat, citi, took, around, 1, hour, kowlon, k..."

# Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer 
wl=WordNetLemmatizer()

def lemmatiz(list):
    lem_text=[wl.lemmatize(word) for word in list]
    return lem_text


df['lem']=df['word'].apply(lambda x:lemmatiz(x))
df.head()

,Rating,Reviewer_Location,Review_Text,Branch,text,word,stem,lem
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...,"[youve, ever, disneyland, anywhere, youll, fin...","[youv, ever, disneyland, anywher, youll, find,...","[youve, ever, disneyland, anywhere, youll, fin..."
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...,"[since, last, time, visit, hk, disneyland, yet...","[sinc, last, time, visit, hk, disneyland, yet,...","[since, last, time, visit, hk, disneyland, yet..."
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...,"[thanks, god, hot, humid, visiting, park, othe...","[thank, god, hot, humid, visit, park, otherwis...","[thanks, god, hot, humid, visiting, park, othe..."
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland great compact park unfortunately...,"[hk, disneyland, great, compact, park, unfortu...","[hk, disneyland, great, compact, park, unfortu...","[hk, disneyland, great, compact, park, unfortu..."
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,location city took around 1 hour kowlon kids l...,"[location, city, took, around, 1, hour, kowlon...","[locat, citi, took, around, 1, hour, kowlon, k...","[location, city, took, around, 1, hour, kowlon..."

# Preparing data

In [ ]:
def listToString(s):
    str1 = " "
    return (str1.join(s))
      
df['final_text']=df['lem'].apply(lambda s:listToString(s))
df.head()

,Rating,Reviewer_Location,Review_Text,Branch,text,word,stem,lem,final_text
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...,"[youve, ever, disneyland, anywhere, youll, fin...","[youv, ever, disneyland, anywher, youll, find,...","[youve, ever, disneyland, anywhere, youll, fin...",youve ever disneyland anywhere youll find disn...
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...,"[since, last, time, visit, hk, disneyland, yet...","[sinc, last, time, visit, hk, disneyland, yet,...","[since, last, time, visit, hk, disneyland, yet...",since last time visit hk disneyland yet time s...
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...,"[thanks, god, hot, humid, visiting, park, othe...","[thank, god, hot, humid, visit, park, otherwis...","[thanks, god, hot, humid, visiting, park, othe...",thanks god hot humid visiting park otherwise w...
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong,hk disneyland great compact park unfortunately...,"[hk, disneyland, great, compact, park, unfortu...","[hk, disneyland, great, compact, park, unfortu...","[hk, disneyland, great, compact, park, unfortu...",hk disneyland great compact park unfortunately...
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong,location city took around 1 hour kowlon kids l...,"[location, city, took, around, 1, hour, kowlon...","[locat, citi, took, around, 1, hour, kowlon, k...","[location, city, took, around, 1, hour, kowlon...",location city took around 1 hour kowlon kid li...

In [ ]:
df1=df.drop(['text','word','stem','Review_Text'], axis=1)
df1.head()

,Rating,Reviewer_Location,Branch,lem,final_text
0,4,Australia,Disneyland_HongKong,"[youve, ever, disneyland, anywhere, youll, fin...",youve ever disneyland anywhere youll find disn...
1,4,Philippines,Disneyland_HongKong,"[since, last, time, visit, hk, disneyland, yet...",since last time visit hk disneyland yet time s...
2,4,United Arab Emirates,Disneyland_HongKong,"[thanks, god, hot, humid, visiting, park, othe...",thanks god hot humid visiting park otherwise w...
3,4,Australia,Disneyland_HongKong,"[hk, disneyland, great, compact, park, unfortu...",hk disneyland great compact park unfortunately...
4,4,United Kingdom,Disneyland_HongKong,"[location, city, took, around, 1, hour, kowlon...",location city took around 1 hour kowlon kid li...

**Add Label encoder to Reviewer_Loaction and Branch columns**

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['encoded_branch'] = le.fit_transform(df.Branch)
df['encoded_reviewer_location']=le.fit_transform(df.Reviewer_Location)
df.head(3)

,Rating,Reviewer_Location,Review_Text,Branch,text,word,stem,lem,final_text,encoded_branch,encoded_reviewer_location
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong,youve ever disneyland anywhere youll find disn...,"[youve, ever, disneyland, anywhere, youll, fin...","[youv, ever, disneyland, anywher, youll, find,...","[youve, ever, disneyland, anywhere, youll, fin...",youve ever disneyland anywhere youll find disn...,1,8
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong,since last time visit hk disneyland yet time s...,"[since, last, time, visit, hk, disneyland, yet...","[sinc, last, time, visit, hk, disneyland, yet,...","[since, last, time, visit, hk, disneyland, yet...",since last time visit hk disneyland yet time s...,1,114
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong,thanks god hot humid visiting park otherwise w...,"[thanks, god, hot, humid, visiting, park, othe...","[thank, god, hot, humid, visit, park, otherwis...","[thanks, god, hot, humid, visiting, park, othe...",thanks god hot humid visiting park otherwise w...,1,151

**Add vectorization methods like count & tf-idf also check for other relevant processing**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [ ]:
Y=df.Rating
Y.head(3)

0    4
1    4
2    4
Name: Rating, dtype: int64

In [ ]:
vec=CountVectorizer(max_features=3000)
X_vec=vec.fit_transform(df['final_text']).toarray()
X_vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

# Diff. classifiers

**NBclassifier**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X_vec, Y, random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
nb=GaussianNB()
nb.fit(X_train,y_train)
print(nb.score(X_train,y_train), nb.score(X_test,y_test))

0.43876594148537135 0.4028507126781695

**SVM**

In [ ]:
#from sklearn.svm import SVC

In [ ]:
svc=SVC()
svc.fit(X_train,y_train)
print(svc.score(X_train,y_train), svc.score(X_test,y_test))

**KNN**

In [ ]:
#from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
print(knn.score(X_train,y_train), knn.score(X_test,y_test))

## preparing data with more than 1 column for models

In [ ]:
X=df.drop(['lem', 'Review_Text', 'word', 'stem', 'text', 'Rating','Branch','Reviewer_Location'], axis=1)
y=df['Rating']
X

In [ ]:
y.value_counts()